# Generated by Django 4.2.8 on 2023-12-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Заголовок")),
                (
                    "title_kz",
                    models.CharField(
                        blank=True, null=True, verbose_name="Заголовок KZ"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, null=True, verbose_name="Заголовок EN"
                    ),
                ),
                ("subtitle", models.CharField(verbose_name="Пододзаголовок")),
                (
                    "subtitle_kz",
                    models.CharField(
                        blank=True, null=True, verbose_name="Пододзаголовок KZ"
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True, null=True, verbose_name="Пододзаголовок EN"
                    ),
                ),
                (
                    "brief_description",
                    models.CharField(verbose_name="Краткое описание"),
                ),
                (
                    "brief_description_kz",
                    models.CharField(
                        blank=True, null=True, verbose_name="Краткое описание KZ"
                    ),
                ),
                (
                    "brief_description_en",
                    models.CharField(
                        blank=True, null=True, verbose_name="Краткое описание EN"
                    ),
                ),
                (
                    "detailed_description",
                    models.TextField(verbose_name="Подробное описание"),
                ),
                (
                    "detailed_description_kz",
                    models.TextField(
                        blank=True, null=True, verbose_name="Подробное описание KZ"
                    ),
                ),
                (
                    "detailed_description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Подробное описание EN"
                    ),
                ),
                (
                    "top_background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about/",
                        verbose_name="Изображение верхнее",
                    ),
                ),
                (
                    "middle_background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about/",
                        verbose_name="Изображение в середине",
                    ),
                ),
            ],
            options={
                "verbose_name": "О нас",
                "verbose_name_plural": "О нас",
            },
        ),
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Заголовок")),
                (
                    "title_kz",
                    models.CharField(
                        blank=True, null=True, verbose_name="Заголовок KZ"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, null=True, verbose_name="Заголовок EN"
                    ),
                ),
                ("subtitle", models.TextField(verbose_name="Подзаголовок")),
                (
                    "subtitle_kz",
                    models.TextField(
                        blank=True, null=True, verbose_name="Подзаголовок KZ"
                    ),
                ),
                (
                    "subtitle_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Подзаголовок EN"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="advantage/", verbose_name="Изображение верхнее"
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
            },
        ),
        migrations.CreateModel(
            name="AdvantageMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Заголовок")),
                (
                    "title_kz",
                    models.CharField(
                        blank=True, null=True, verbose_name="Заголовок KZ"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, null=True, verbose_name="Заголовок  EN"
                    ),
                ),
                ("subtitle", models.TextField(verbose_name="Подзаголовок")),
                (
                    "subtitle_kz",
                    models.TextField(
                        blank=True, null=True, verbose_name="Подзаголовок KZ"
                    ),
                ),
                (
                    "subtitle_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Подзаголовок EN"
                    ),
                ),
                (
                    "top_background_image",
                    models.ImageField(
                        upload_to="advantage/", verbose_name="Изображение верхнее"
                    ),
                ),
            ],
            options={
                "verbose_name": "Главное преимущество",
                "verbose_name_plural": "Главное преимущество",
            },
        ),
        migrations.CreateModel(
            name="CallbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=16, verbose_name="Номер телефона"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ звонка",
                "verbose_name_plural": "Заказы звонков",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(verbose_name="Адрес")),
                (
                    "address_kz",
                    models.CharField(blank=True, null=True, verbose_name="Адрес KZ"),
                ),
                (
                    "address_en",
                    models.CharField(blank=True, null=True, verbose_name="Адрес EN"),
                ),
                ("phone", models.CharField(verbose_name="Номер телефона")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Название")),
                (
                    "title_kz",
                    models.CharField(blank=True, null=True, verbose_name="Название KZ"),
                ),
                (
                    "title_en",
                    models.CharField(blank=True, null=True, verbose_name="Название EN"),
                ),
                ("subtitle", models.CharField(verbose_name="Подзаголовок")),
                (
                    "subtitle_kz",
                    models.CharField(
                        blank=True, null=True, verbose_name="Подзаголовок KZ"
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True, null=True, verbose_name="Подзаголовок EN"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "description_kz",
                    models.TextField(blank=True, null=True, verbose_name="Описание KZ"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Описание EN"),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступность"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Заголовок")),
                ("title_kz", models.CharField(verbose_name="Заголовок KZ")),
                ("title_en", models.CharField(verbose_name="Заголовок EN")),
                (
                    "subtitle",
                    models.TextField(
                        blank=True, null=True, verbose_name="Подзаголовок"
                    ),
                ),
                (
                    "subtitle_kz",
                    models.TextField(
                        blank=True, null=True, verbose_name="Подзаголовок KZ"
                    ),
                ),
                (
                    "subtitle_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Подзаголовок EN"
                    ),
                ),
            ],
            options={
                "verbose_name": "Галерея",
                "verbose_name_plural": "Галерея",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Название")),
                (
                    "title_kz",
                    models.CharField(blank=True, null=True, verbose_name="Название KZ"),
                ),
                (
                    "title_en",
                    models.CharField(blank=True, null=True, verbose_name="Название EN"),
                ),
                ("subtitle", models.CharField(verbose_name="Подзаголовок")),
                (
                    "subtitle_kz",
                    models.CharField(
                        blank=True, null=True, verbose_name="Подзаголовок KZ"
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True, null=True, verbose_name="Подзаголовок EN"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "description_kz",
                    models.TextField(blank=True, null=True, verbose_name="Описание KZ"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Описание EN"),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступность"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Номер",
                "verbose_name_plural": "Номера",
            },
        ),
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.ImageField(upload_to="", verbose_name="Иконка")),
                ("link", models.URLField(verbose_name="Ссылка")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_networks",
                        to="information.contact",
                        verbose_name="Социальные сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_image",
                    models.ImageField(
                        upload_to="room/", verbose_name="Изображение номера"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_images",
                        to="information.room",
                        verbose_name="Связанный номер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение номера",
                "verbose_name_plural": "Изображения номеров",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gallery_image",
                    models.ImageField(
                        upload_to="gallery/", verbose_name="Изображение для галереи"
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="information.gallery",
                        verbose_name="Галерея",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение галереи",
                "verbose_name_plural": "Изображения галереи",
            },
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_image",
                    models.ImageField(
                        upload_to="event/", verbose_name="Изображение номера"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_images",
                        to="information.event",
                        verbose_name="Связанный номер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение мероприятия",
                "verbose_name_plural": "Изображения мероприятий",
            },
        ),
        migrations.CreateModel(
            name="BookingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата заезда")),
                ("end_date", models.DateField(verbose_name="Дата выезда")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_events",
                        to="information.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование мероприятия",
                "verbose_name_plural": "Бронирования мероприятий",
            },
        ),
    ]
